# TRANSLATOR
px_per_mm: 6

# CAMERA
camera:
  resolution:
    - 3280
    - 2464
  matrix:
    - - 2618.17578125
      - 0.0
      - 1650.9212646484375
    - - 0.0
      - 2618.591064453125
      - 1182.888427734375
    - - 0.0
      - 0.0
      - 3.0799999237060547
  dist_coeffs:
    - 0.14257140457630157
    - 0.0471414290368557
    - -0.007883399724960327
    - -0.003448320087045431
    - -0.8946049213409424

# BOARD
board:
  dict_name: DICT_6X6_50
  ids:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  object_points:
  - - - 0.0
      - 0.0
      - 0.0
    - - 40.0
      - 0.0
      - 0.0
    - - 40.0
      - 40.0
      - 0.0
    - - 0.0
      - 40.0
      - 0.0
  - - - 0.0
      - 50.0
      - 0.0
    - - 40.0
      - 50.0
      - 0.0
    - - 40.0
      - 90.0
      - 0.0
    - - 0.0
      - 90.0
      - 0.0
  - - - 0.0
      - 100.0
      - 0.0
    - - 40.0
      - 100.0
      - 0.0
    - - 40.0
      - 140.0
      - 0.0
    - - 0.0
      - 140.0
      - 0.0
  - - - 0.0
      - 150.0
      - 0.0
    - - 40.0
      - 150.0
      - 0.0
    - - 40.0
      - 190.0
      - 0.0
    - - 0.0
      - 190.0
      - 0.0
  - - - 0.0
      - 200.0
      - 0.0
    - - 40.0
      - 200.0
      - 0.0
    - - 40.0
      - 240.0
      - 0.0
    - - 0.0
      - 240.0
      - 0.0
  - - - 0.0
      - 250.0
      - 0.0
    - - 40.0
      - 250.0
      - 0.0
    - - 40.0
      - 290.0
      - 0.0
    - - 0.0
      - 290.0
      - 0.0
  - - - 0.0
      - 300.0
      - 0.0
    - - 40.0
      - 300.0
      - 0.0
    - - 40.0
      - 340.0
      - 0.0
    - - 0.0
      - 340.0
      - 0.0
  - - - 50.0
      - 300.0
      - 0.0
    - - 90.0
      - 300.0
      - 0.0
    - - 90.0
      - 340.0
      - 0.0
    - - 50.0
      - 340.0
      - 0.0
  - - - 100.0
      - 300.0
      - 0.0
    - - 140.0
      - 300.0
      - 0.0
    - - 140.0
      - 340.0
      - 0.0
    - - 100.0
      - 340.0
      - 0.0
  - - - 150.0
      - 300.0
      - 0.0
    - - 190.0
      - 300.0
      - 0.0
    - - 190.0
      - 340.0
      - 0.0
    - - 150.0
      - 340.0
      - 0.0
  - - - 200.0
      - 300.0
      - 0.0
    - - 240.0
      - 300.0
      - 0.0
    - - 240.0
      - 340.0
      - 0.0
    - - 200.0
      - 340.0
      - 0.0
  - - - 250.0
      - 300.0
      - 0.0
    - - 290.0
      - 300.0
      - 0.0
    - - 290.0
      - 340.0
      - 0.0
    - - 250.0
      - 340.0
      - 0.0
  - - - 300.0
      - 300.0
      - 0.0
    - - 340.0
      - 300.0
      - 0.0
    - - 340.0
      - 340.0
      - 0.0
    - - 300.0
      - 340.0
      - 0.0
  - - - 300.0
      - 250.0
      - 0.0
    - - 340.0
      - 250.0
      - 0.0
    - - 340.0
      - 290.0
      - 0.0
    - - 300.0
      - 290.0
      - 0.0
  - - - 300.0
      - 200.0
      - 0.0
    - - 340.0
      - 200.0
      - 0.0
    - - 340.0
      - 240.0
      - 0.0
    - - 300.0
      - 240.0
      - 0.0
  - - - 300.0
      - 150.0
      - 0.0
    - - 340.0
      - 150.0
      - 0.0
    - - 340.0
      - 190.0
      - 0.0
    - - 300.0
      - 190.0
      - 0.0
  - - - 300.0
      - 100.0
      - 0.0
    - - 340.0
      - 100.0
      - 0.0
    - - 340.0
      - 140.0
      - 0.0
    - - 300.0
      - 140.0
      - 0.0
  - - - 300.0
      - 50.0
      - 0.0
    - - 340.0
      - 50.0
      - 0.0
    - - 340.0
      - 90.0
      - 0.0
    - - 300.0
      - 90.0
      - 0.0
  - - - 300.0
      - 0.0
      - 0.0
    - - 340.0
      - 0.0
      - 0.0
    - - 340.0
      - 40.0
      - 0.0
    - - 300.0
      - 40.0
      - 0.0

  size:
    - 340
    - 340

  roi_bounds:
    - 50
    - 50
    - 290
    - 290


# PLOTTER
plotter:
  port: /dev/ttyACM0
  baudrate: 115200
  commands:
    SET_POSITION: |
      G10 P0 L20 X{x} Y{y} Z0
    MOVE_TO: |
      G1 X{x} Y{y} F16300
    FAST_MOVE_TO: |
      G0 X{x} Y{y}
    PEN_UP: |
      M4 S600
      G4 P0.1
    PEN_DOWN: |
      M4 S960
      G4 P0.1
  away:
    - -38
    - 227
